blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    #url(r'^$',views.PostListView.as_view(),name='post_list'),
    # post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,name='post_detail'),

]

vanguards/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^',include('home.urls',namespace='home',app_name='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^podcast/',include('podcast.urls',namespace='podcast',app_name='podcast')),
    url(r'^gallery/',include('gallery.urls',namespace='gallery')),
    url(r'^gallery/',include('photologue.urls', namespace='photologue'))
]


#iistore nya ang mga media habang hindi pa nakaup yung site
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from taggit.managers import TaggableManager



class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')



class Post(models.Model):
    STATUS_CHOICES = {
        ('draft','Draft'),
        ('published','Published'),
    }

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,related_name='blog_posts')
    body = models.TextField()
    heroImg = models.FileField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now= True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES, default= 'draft')


    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    #canonical url for post objects

    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                                self.publish.strftime('%m'),
                                                self.publish.strftime('%d'),
                                                self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments')
    name = models.CharField(max_length=50)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ('created',)

        def __str__(self):
            return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import CommentForm



def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/list.html'

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True)
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags',
                                                                             '-publish')[:4]

    return render(request, 'blog/detail.html', {'post': post,
                                                     'comments': comments,
                                                     'comment_form': comment_form,
                                                     'similar_posts':similar_posts})

blog/templates/blog/detail.html
{% extends 'base.html' %}



{% block content %}

    <h2>{{ post.title }}</h2>
    <p>Publish|<i>{{ post.publish }} by</i> {{ post.author }}</p>
    <img src="{{ post.heroImg.url }}" width="100px"><br><br>
    <p>{{ post.body|linebreaks }}{% lorem 3 p %}</p>
    <h2>Similar Posts</h2>
    {% for post in similar_posts %}
        <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
    {% empty %}
        <p>There are no similar posts yet</p>
    {% endfor %}

    {% with comments.count as total_comments %}
        <h3>{{ total_comments }} Comment{{ total_comments|pluralize }}</h3>
    {% endwith %}

    {% for comment in comments %}
        <div class="" id="comments">
            <p>Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}</p>
            <p>{{ comment.body|linebreaks }}</p>
        </div>

    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h3>Add a new comment</h3>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add Comment"></p>


        </form>
    {% endif %}



{% endblock %}

blog/templates/blog/list.html
{% extends 'base.html' %}


{% block content %}
    <h1>Blogg</h1>
    <div class="container col-md-8">
        {% for post in posts %}
            <h3><a href="{{  post.get_absolute_url }}">{{ post.title }}</a></h3>
            {% for tag in post.tags.all %}
                <a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
            <p>Publish | <i>{{ post.publish }}</i> by {{ post.author }}</p>
            <p>{{ post.body|linebreaks|truncatewords_html:30 }}</p>
            <p><a href="{{ post.get_absolute_url }}">Read more..</a></p>
        {% endfor %}
    </div>


{% endblock %}