blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns =[
    #url(r'^$',views.PostListView.as_view(),name='post_list'),
    # post views
    url(r'^$', views.post_list, name='post_list'),
    url(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list, name='post_list_by_tag'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
        views.post_detail,name='post_detail'),

]

home/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$',views.HomeView.as_view(),name='home'),
]

vanguards/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    url(r'^',include('home.urls',namespace='home',app_name='home')),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog',app_name='blog')),
    url(r'^podcast/',include('podcast.urls',namespace='podcast',app_name='podcast')),
    url(r'^gallery/',include('gallery.urls',namespace='gallery')),
    url(r'^gallery/',include('photologue.urls', namespace='photologue'))
]


#iistore nya ang mga media habang hindi pa nakaup yung site
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root= settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
#
#
# class City(models.Model):
#     name= models.CharField(max_length=250)

home/forms.py
# from django import forms
# from mapwidgets.widgets import GooglePointFieldWidget
#
#
# class CityAdminForm(forms.ModelForm):
#     class Meta:
#         model = City
#         fields = ("coordinates", "city_hall")
#         widgets = {'coordinates': GooglePointFieldWidget,'city_hall': GooglePointFieldWidget,}

home/views.py
from django.shortcuts import render
from django.views import generic


class HomeView(generic.TemplateView):
    template_name = 'home.html'

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:700" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/css/styles.css' %}">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">

      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" style="font-family: 'Montserrat', sans-serif;" href="{% url 'home:home' %}">VANGUARDS</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'home:home' %}">Home</a></li>
            <li><a href="{% url 'blog:post_list' %}">Blog</a></li>
            <li><a href="{% url 'podcast:index' %}">Podcast</a></li>
            <li><a href="{% url 'gallery:galleryindex' %}">Gallery</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Contact</a></li>

          </ul>

        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->


    </div>
</nav><!-- /.navbar -->

<div class="container-fluid">
    {% block content %}
    {% endblock %}



</div>





<script src="{% static 'blog/js/jquery-3.2.1.js' %}" type="text/javascript" rel="script"></script>
<script src="{% static 'blog/js/bootstrap.js' %} " type="text/javascript" rel="script"></script>
<script src="{% static 'blog/js/parallax.min.js' %}"></script>
<script src="{%  static 'blog/js/nav-shrink.js' %}"></script>
<script src="https://maps.googleapis.com/maps/api/js?callback=require"></script>

<script>

$('.parallax-window').parallax();


function myMap() {
    var myLatLng = {lat: 15.185224, lng: 120.583102};
    var mapOptions = {
        center: myLatLng,
        zoom: 19,
        mapTypeId: google.maps.MapTypeId.HYBRID
    }
    var map = new google.maps.Map(document.getElementById("map"), mapOptions);
    var marker = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: 'Dau Christian Community Church'
    });
}

myMap()




</script>


</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}

    <div class="parallax-window" data-parallax="scroll" data-image-src="#slider">
        <div class="col-md-12 ">
                <div class="carousel slide" data-ride="carousel" id="slider">
                    <ol class="carousel-indicators">
                        <li data-target="#slider" data-slide-to="0" class="active"></li>
                        <li data-target="#slider" data-slide-to="1" ></li>
                        <li data-target="#slider" data-slide-to="2" ></li>
                        <li data-target="#slider" data-slide-to="3" ></li>
                    </ol>
                    <div class="carousel-inner" style="height: 700px" >
                        <div class="item active">
                            <img class="cover" src="{% static 'home/slider-1.jpg' %}">

                        </div>
                        <div class="item ">
                            <img class="cover"  src="{% static 'home/slider-2.jpg' %}">
                        </div>
                        <div  class="item ">
                            <img class="cover"  src="{% static 'home/slider-3.jpg' %}">
                        </div>
                        <div class="item">
                            <img class="cover"  src="{% static 'home/slider-4.jpg' %}">
                        </div>

                    </div>

                    <a href="#slider" data-slide = "prev" class="left carousel-control">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                    </a>
                    <a href="#slider" data-slide = "next" class="right carousel-control">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                    </a>

                </div>
            </div>






    </div>
    <div class="window-wrapper">
        <h1>My Maps</h1>
        <div id="map" style="width:500px;height:300px"></div>


    </div>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{%  static 'background/bg_2.jpeg' %}"></div>
    <div class="window-wrapper"></div>
    <div class="parallax-window" data-parallax="scroll" data-image-src="{%  static 'background/bg_1.jpeg' %}"></div>
    <div class="window-wrapper"></div>

{% endblock %}